### ISSUE TITLE
pdfseparate/poppler are undocumented dependencies

### ISSUE THREAD

**Issue by aresnick** [trieloff/key2svg#1]
It looks like `pdfseparate` is a requirement, which on Mac OS X can be fulfilled with `brew install poppler`.  Without this, when running `key2svg` with [floorplan.key.zip](https://github.com/trieloff/key2svg/files/1503459/floorplan.key.zip) I receive the following error after the Keynote window containing that file receives focus:

```
❯ ./key2svg.sh /Users/aresnick/Desktop/floorplan.key
/Users/aresnick/Documents/floorplan-2
./key2svg.sh: line 106: pdfseparate: command not found
File -> /Users/aresnick/Documents/floorplan-2-*.pdf
GPL Ghostscript 9.22 (2017-10-04)
Copyright (C) 2017 Artifex Software, Inc.  All rights reserved.
This software comes with NO WARRANTY: see the file PUBLIC for details.
Error: /undefinedfilename in (/Users/aresnick/Documents/floorplan-2-*.pdf)
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push
Dictionary stack:
   --dict:981/1684(ro)(G)--   --dict:0/20(G)--   --dict:78/200(L)--
Current allocation mode is local
Last OS error: No such file or directory
GPL Ghostscript 9.22: Unrecoverable error, exit code 1
```

This is on macOS Sierra, 10.12.6, with Keynote version 7.3.1 (5249), ghostscript 9.22, Inkscape 0.92.2 5c3e80d, and XQuartz 2.7.11 (xorg-server 1.18.4).

To install `pdfseparate`, I had to `brew unlink xpdf` and then `brew install poppler` ([via StackOverflow](https://superuser.com/questions/827462/how-can-i-split-a-pdf-file-into-single-pages-quickly-i-e-from-the-terminal-com)).

After doing so, `key2svg` succeeds.

Thanks!  This is awesome—

**Comment by trieloff** [comment]
Thanks for reporting + providing a resolution. I’ve updated the README

**Comment by aresnick** [comment]
No problem; thanks for such a nice tool!

**Comment by aresnick** [comment]
Oh I think you just need `brew install poppler`— I don't believe `brew install pdfseparate` works.

**Comment by aresnick** [comment]
```
❯ brew install pdfseparate
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

Error: No available formula with the name "pdfseparate" 
==> Searching for a previously deleted formula...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```
